Cerca fix, and unit test
tierneytim/OPM pull request #14
Opened 2022-06-30 10:12 UTC by georgeoneill

Test data and unit test added, as well as fix in situations where sensor locations not being present cause spm_opm_create to fail.

2022-06-30 10:35 UTC, tierneytim requested changes
there is no need for more than 1 second of data for testing purposes. please chop the data before trying to upload. Then undo the zipping and remove code relating to unzipping

2022-06-30 10:48 UTC, georgeoneill commented
I thought this might be the case, on it.

2022-06-30 12:38 UTC, georgeoneill commented
This should now include the 1-second long dataset instead of the 90 second dataset

2022-07-04 10:21 UTC, tierneytim approved these changes

2022-07-04 10:21 UTC, merged